db:
  image: postgres
  ports: 
    - "5432:5432"
  environment:
    POSTGRES_USER: vicrun
    POSTGRES_PASSWORD: vicrun57a
web:
  build: .
  volumes:
    - ./vicrun-server:/home/app/vicrun
  ports: 
    - "5780:5780"
  links: 
    - db
